const fs = require('fs');
const file = 'c:/Users/admin/Desktop/CongTyInQuangPhat/frontend/src/screens/admin/FinanceCenterScreen.jsx';
let content = fs.readFileSync(file, 'utf8');

const replacements = [
  ['So quy & Dong tien', 'Sổ quỹ & Dòng tiền'],
  ['Phai thu', 'Phải thu'],
  ['Phai tra', 'Phải trả'],
  ['Khong the tai du lieu tai chinh', 'Không thể tải dữ liệu tài chính'],
  ['Da cap nhat so quy', 'Đã cập nhật sổ quỹ'],
  ['Da tao so quy moi', 'Đã tạo sổ quỹ mới'],
  ['Khong the luu so quy', 'Không thể lưu sổ quỹ'],
  ['Da cap nhat danh muc', 'Đã cập nhật danh mục'],
  ['Da tao danh muc moi', 'Đã tạo danh mục mới'],
  ['Khong the luu danh muc', 'Không thể lưu danh mục'],
  ['Da cap nhat chung tu goc', 'Đã cập nhật chứng từ gốc'],
  ['Da tao chung tu goc', 'Đã tạo chứng từ gốc'],
  ['Khong the luu chung tu goc', 'Không thể lưu chứng từ gốc'],
  ['Da ghi so phieu giao dich', 'Đã ghi sổ phiếu giao dịch'],
  ['Khong the ghi so phieu giao dich', 'Không thể ghi sổ phiếu giao dịch'],
  ['Nhap ly do huy phieu', 'Nhập lý do hủy phiếu'],
  ['Nhap sai nghiep vu', 'Nhập sai nghiệp vụ'],
  ['Da huy phieu giao dich', 'Đã hủy phiếu giao dịch'],
  ['Khong the huy phieu giao dich', 'Không thể hủy phiếu giao dịch'],
  ['Da nhap so du dau ky', 'Đã nhập số dư đầu kỳ'],
  ['so quy,', 'sổ quỹ,'],
  ['cong no', 'công nợ'],
  ['Khong the nhap so du dau ky', 'Không thể nhập số dư đầu kỳ'],
  ['Xoa so quy', 'Xóa sổ quỹ'],
  ['Ban chac chan muon xoa so quy', 'Bạn chắc chắn muốn xóa sổ quỹ'],
  ['Da xoa so quy', 'Đã xóa sổ quỹ'],
  ['Khong the xoa so quy', 'Không thể xóa sổ quỹ'],
  ['Xoa danh muc', 'Xóa danh mục'],
  ['Ban chac chan muon xoa danh muc', 'Bạn chắc chắn muốn xóa danh mục'],
  ['Da xoa danh muc', 'Đã xóa danh mục'],
  ['Khong the xoa danh muc', 'Không thể xóa danh mục'],
  ['Chung tu', 'Chứng từ'],
  ['Doi tuong', 'Đối tượng'],
  ['Lien ket', 'Liên kết'],
  ['Con no', 'Còn nợ'],
  ['Trang thai', 'Trạng thái'],
  ['Hanh dong', 'Hành động'],
  ['Khong lien ket', 'Không liên kết'],
  ['Thu tien', 'Thu tiền'],
  ['Chi tien', 'Chi tiền'],
  ['Chua co chung tu cong no nao.', 'Chưa có chứng từ công nợ nào.'],
  ['Dang tai trung tam tai chinh...', 'Đang tải trung tâm tài chính...'],
  ['Trung tam tai chinh', 'Trung tâm tài chính'],
  ['Quan ly so quy, chung tu goc, phieu giao dich va cong no AR/AP tren cung mot luong.', 'Quản lý sổ quỹ, chứng từ gốc, phiếu giao dịch và công nợ AR/AP trên cùng một luồng.'],
  ['Tao phieu', 'Tạo phiếu'],
  ['Nhap so du dau ky', 'Nhập số dư đầu kỳ'],
  ['Xem dashboard', 'Xem dashboard'],
  ['Tong tien hien co', 'Tổng tiền hiện có'],
  ['Thu 30 ngay', 'Thu 30 ngày'],
  ['Chi 30 ngay', 'Chi 30 ngày'],
  ['Cong no rong', 'Công nợ ròng'],
  ['So quy', 'Sổ quỹ'],
  ['so quy', 'sổ quỹ'],
  ['So du thuc te tai cac tai khoan tien mat va ngan hang.', 'Số dư thực tế tại các tài khoản tiền mặt và ngân hàng.'],
  ['Danh muc thu chi', 'Danh mục thu chi'],
  ['Them so quy', 'Thêm sổ quỹ'],
  ['Dong tien theo so quy', 'Dòng tiền theo sổ quỹ'],
  ['Xem lich su phat sinh Thu / Chi / Chuyen quy theo tung tai khoan.', 'Xem lịch sử phát sinh Thu / Chi / Chuyển quỹ theo từng tài khoản.'],
  ['Tai khoan dang xem', 'Tài khoản đang xem'],
  ['Chua chon', 'Chưa chọn'],
  ['So du hien tai', 'Số dư hiện tại'],
  ['Phieu', 'Phiếu'],
  ['Loai', 'Loại'],
  ['Gia tri', 'Giá trị'],
  ['Chua co giao dich nao cho tai khoan nay.', 'Chưa có giao dịch nào cho tài khoản này.'],
  ['Phieu giao dich', 'Phiếu giao dịch'],
  ['Lap phieu Thu / Chi / Chuyen quy, upload hoa don va ghi so ngay lap tuc.', 'Lập phiếu Thu / Chi / Chuyển quỹ, upload hóa đơn và ghi sổ ngay lập tức.'],
  ['Tao phieu moi', 'Tạo phiếu mới'],
  ['Tai khoan', 'Tài khoản'],
  ['Chung tu goc', 'Chứng từ gốc'],
  ['Dinh kem', 'Đính kèm'],
  ['Khong allocate', 'Không allocate'],
  ['Khong co file', 'Không có file'],
  ['Da huy', 'Đã hủy'],
  ['Chua co phieu giao dich nao.', 'Chưa có phiếu giao dịch nào.'],
  ['Cong no phai thu', 'Công nợ phải thu'],
  ['Theo doi cac chung tu ban hang / opening balance va lap phieu thu truc tiep.', 'Theo dõi các chứng từ bán hàng / opening balance và lập phiếu thu trực tiếp.'],
  ['Tao chung tu phai thu', 'Tạo chứng từ phải thu'],
  ['Tong phai thu', 'Tổng phải thu'],
  ['So chung tu mo', 'Số chứng từ mở'],
  ['Cong no phai tra', 'Công nợ phải trả'],
  ['Theo doi cong no nha cung cap va lap phieu chi ngay tren tung chung tu.', 'Theo dõi công nợ nhà cung cấp và lập phiếu chi ngay trên từng chứng từ.'],
  ['Tao chung tu phai tra', 'Tạo chứng từ phải trả'],
  ['Tong phai tra', 'Tổng phải trả'],
  ['Cap nhat so quy', 'Cập nhật sổ quỹ'],
  ['Tao so quy moi', 'Tạo sổ quỹ mới'],
  ['Ma so quy', 'Mã sổ quỹ'],
  ['Ten so quy', 'Tên sổ quỹ'],
  ['Loai tai khoan', 'Loại tài khoản'],
  ['So du dau ky', 'Số dư đầu kỳ'],
  ['Ngan hang', 'Ngân hàng'],
  ['So tai khoan', 'Số tài khoản'],
  ['Kich hoat so quy', 'Kích hoạt sổ quỹ'],
  ['Dang luu...', 'Đang lưu...'],
  ['Luu so quy', 'Lưu sổ quỹ'],
  ['Ma danh muc', 'Mã danh mục'],
  ['Ten danh muc', 'Tên danh mục'],
  ['Mo ta', 'Mô tả'],
  ['Danh muc dang hoat dong', 'Danh mục đang hoạt động'],
  ['Cap nhat', 'Cập nhật'],
  ['Tao danh muc', 'Tạo danh mục'],
  ['Moi', 'Mới'],
  ['Da xoa', 'Đã xóa'],
  ['Cap nhat chung tu goc', 'Cập nhật chứng từ gốc'],
  ['Tao chung tu goc', 'Tạo chứng từ gốc'],
  ['Loai chung tu', 'Loại chứng từ'],
  ['Chon doi tuong', 'Chọn đối tượng'],
  ['Khong chon', 'Không chọn'],
  ['Chon so quy', 'Chọn sổ quỹ'],
  ['Chon danh muc', 'Chọn danh mục'],
  ['Chon lien ket', 'Chọn liên kết'],
  ['Tong gia tri', 'Tổng giá trị'],
  ['Ghi chu', 'Ghi chú'],
  ['Luu chung tu', 'Lưu chứng từ'],
  ['Lap phieu giao dich', 'Lập phiếu giao dịch'],
  ['Loai phieu', 'Loại phiếu'],
  ['Ngay giao dich', 'Ngày giao dịch'],
  ['So tien', 'Số tiền'],
  ['Tai khoan nguon / nhan', 'Tài khoản nguồn / nhận'],
  ['Tai khoan dich', 'Tài khoản đích'],
  ['Chon tai khoan dich', 'Chọn tài khoản đích'],
  ['Danh muc', 'Danh mục'],
  ['Allocate vao chung tu goc', 'Allocate vào chứng từ gốc'],
  ['Ho tro mot hoac nhieu chung tu phai thu / phai tra.', 'Hỗ trợ một hoặc nhiều chứng từ phải thu / phải trả.'],
  ['Them dong', 'Thêm dòng'],
  ['Khong can chung tu', 'Không cần chứng từ'],
  ['Con ', 'Còn '],
  ['So tien allocate', 'Số tiền allocate'],
  ['Upload hoa don / chung tu', 'Upload hóa đơn / chứng từ'],
  ['Chon PDF, JPG, PNG, WEBP', 'Chọn PDF, JPG, PNG, WEBP'],
  ['Toi da 10 tep, 10MB / tep', 'Tối đa 10 tệp, 10MB / tệp'],
  ['Preview so du', 'Preview số dư'],
  ['Hien tai', 'Hiện tại'],
  ['Sau giao dich', 'Sau giao dịch'],
  ['Ghi chu nghiep vu', 'Ghi chú nghiệp vụ'],
  ['cong tien vao so quy va giam phai thu neu co allocate.', 'cộng tiền vào sổ quỹ và giảm phải thu nếu có allocate.'],
  ['tru tien khoi so quy va giam phai tra neu co allocate.', 'trừ tiền khỏi sổ quỹ và giảm phải trả nếu có allocate.'],
  ['chi chuyen tien noi bo, khong vao P&L va khong dong vao cong no.', 'chỉ chuyển tiền nội bộ, không vào P&L và không động vào công nợ.'],
  ['Dang ghi so...', 'Đang ghi sổ...'],
  ['Ghi so ngay', 'Ghi sổ ngay'],
  ['So du cac so quy', 'Số dư các sổ quỹ'],
  ['Dung truoc khi phat sinh giao dich production.', 'Dùng trước khi phát sinh giao dịch production.'],
  ['Opening balance phai thu', 'Opening balance phải thu'],
  ['Nhap cac khoan khach hang con no tai thoi diem go-live.', 'Nhập các khoản khách hàng còn nợ tại thời điểm go-live.'],
  ['Opening balance phai tra', 'Opening balance phải trả'],
  ['Nhap cac khoan no nha cung cap tai thoi diem go-live.', 'Nhập các khoản nợ nhà cung cấp tại thời điểm go-live.'],
  ['Chon supplier', 'Chọn supplier'],
  ['Chon customer', 'Chọn customer'],
  ['Ngay lap', 'Ngày lập'],
  ['Han thanh toan', 'Hạn thanh toán'],
  ['Lien ket nghiep vu', 'Liên kết nghiệp vụ']
];

for (let [search, replace] of replacements) {
  content = content.replace(new RegExp(search, 'g'), replace);
}

// specific short words safely
content = content.replace(/>Sua</g, '>Sửa<');
content = content.replace(/>Xoa</g, '>Xóa<');
content = content.replace(/>Dong</g, '>Đóng<');
content = content.replace(/>Ngay</g, '>Ngày<');

fs.writeFileSync(file, content);
console.log('Replaced all matches');
